package com.letbeclear.model;
// Generated Feb 5, 2018 1:20:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommentsLike generated by hbm2java
 */
@Entity
@Table(name = "comments_like", catalog = "letbeclear")
public class CommentsLike implements java.io.Serializable {

	private Integer likeId;
	private PostComment postComment;
	private Users users;
	private String field1;
	private Integer field2;
	private Date field3;

	public CommentsLike() {
	}

	public CommentsLike(PostComment postComment, Users users, Date field3) {
		this.postComment = postComment;
		this.users = users;
		this.field3 = field3;
	}

	public CommentsLike(PostComment postComment, Users users, String field1, Integer field2, Date field3) {
		this.postComment = postComment;
		this.users = users;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LIKE_ID", unique = true, nullable = false)
	public Integer getLikeId() {
		return this.likeId;
	}

	public void setLikeId(Integer likeId) {
		this.likeId = likeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMMENT_ID", nullable = false)
	public PostComment getPostComment() {
		return this.postComment;
	}

	public void setPostComment(PostComment postComment) {
		this.postComment = postComment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "FIELD1", length = 256)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2")
	public Integer getField2() {
		return this.field2;
	}

	public void setField2(Integer field2) {
		this.field2 = field2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIELD3", nullable = false, length = 19)
	public Date getField3() {
		return this.field3;
	}

	public void setField3(Date field3) {
		this.field3 = field3;
	}

}
