package com.letbeclear.model;
// Generated Feb 5, 2018 1:20:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PostComment generated by hbm2java
 */
@Entity
@Table(name = "post_comment", catalog = "letbeclear")
public class PostComment implements java.io.Serializable {

	private Integer commentId;
	private UserPost userPost;
	private Users users;
	private String comment;
	private String field1;
	private Integer field2;
	private Date field3;
	private Set<CommentsLike> commentsLikes = new HashSet<CommentsLike>(0);
	private Set<CommentsLike> commentsLikes_1= new HashSet<CommentsLike>(0);

	public PostComment() {
	}

	public PostComment(UserPost userPost, Date field3) {
		this.userPost = userPost;
		this.field3 = field3;
	}

	public PostComment(UserPost userPost, Users users, String comment, String field1, Integer field2, Date field3,
			Set<CommentsLike> commentsLikes, Set<CommentsLike> commentsLikes_1) {
		this.userPost = userPost;
		this.users = users;
		this.comment = comment;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.commentsLikes = commentsLikes;
		this.commentsLikes_1 = commentsLikes_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "COMMENT_ID", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POST_ID", nullable = false)
	public UserPost getUserPost() {
		return this.userPost;
	}

	public void setUserPost(UserPost userPost) {
		this.userPost = userPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "COMMENT", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "FIELD1", length = 256)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2")
	public Integer getField2() {
		return this.field2;
	}

	public void setField2(Integer field2) {
		this.field2 = field2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIELD3", nullable = false, length = 19)
	public Date getField3() {
		return this.field3;
	}

	public void setField3(Date field3) {
		this.field3 = field3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postComment")
	public Set<CommentsLike> getCommentsLikes() {
		return this.commentsLikes;
	}

	public void setCommentsLikes(Set<CommentsLike> commentsLikes) {
		this.commentsLikes = commentsLikes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postComment")
	public Set<CommentsLike> getCommentsLikes_1() {
		return this.commentsLikes_1;
	}

	public void setCommentsLikes_1(Set<CommentsLike> commentsLikes_1) {
		this.commentsLikes_1 = commentsLikes_1;
	}

}
