package com.letbeclear.model;
// Generated Feb 5, 2018 1:20:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserReg generated by hbm2java
 */
@Entity
@Table(name = "user_reg", catalog = "letbeclear", uniqueConstraints = @UniqueConstraint(columnNames = "LOGINID"))
public class UserReg implements java.io.Serializable {

	private long userId;
	private Users users;
	private String loginid;
	private String logonpassword;
	private Short passwordexpired;
	private String resetpasswordcode;
	private short timeout;
	private Date passwordcreation;
	private Date resetpasstime;
	private Short passwordinvalid;
	private Integer field1;
	private String field2;
	private String field3;
	private Date field4;

	public UserReg() {
	}

	public UserReg(Users users, String loginid, String logonpassword, short timeout, Date passwordcreation,
			Date resetpasstime, Date field4) {
		this.users = users;
		this.loginid = loginid;
		this.logonpassword = logonpassword;
		this.timeout = timeout;
		this.passwordcreation = passwordcreation;
		this.resetpasstime = resetpasstime;
		this.field4 = field4;
	}

	public UserReg(Users users, String loginid, String logonpassword, Short passwordexpired, String resetpasswordcode,
			short timeout, Date passwordcreation, Date resetpasstime, Short passwordinvalid, Integer field1,
			String field2, String field3, Date field4) {
		this.users = users;
		this.loginid = loginid;
		this.logonpassword = logonpassword;
		this.passwordexpired = passwordexpired;
		this.resetpasswordcode = resetpasswordcode;
		this.timeout = timeout;
		this.passwordcreation = passwordcreation;
		this.resetpasstime = resetpasstime;
		this.passwordinvalid = passwordinvalid;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "LOGINID", unique = true, nullable = false, length = 128)
	public String getLoginid() {
		return this.loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	@Column(name = "LOGONPASSWORD", nullable = false, length = 256)
	public String getLogonpassword() {
		return this.logonpassword;
	}

	public void setLogonpassword(String logonpassword) {
		this.logonpassword = logonpassword;
	}

	@Column(name = "PASSWORDEXPIRED")
	public Short getPasswordexpired() {
		return this.passwordexpired;
	}

	public void setPasswordexpired(Short passwordexpired) {
		this.passwordexpired = passwordexpired;
	}

	@Column(name = "RESETPASSWORDCODE", length = 256)
	public String getResetpasswordcode() {
		return this.resetpasswordcode;
	}

	public void setResetpasswordcode(String resetpasswordcode) {
		this.resetpasswordcode = resetpasswordcode;
	}

	@Column(name = "TIMEOUT", nullable = false)
	public short getTimeout() {
		return this.timeout;
	}

	public void setTimeout(short timeout) {
		this.timeout = timeout;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PASSWORDCREATION", nullable = false, length = 19)
	public Date getPasswordcreation() {
		return this.passwordcreation;
	}

	public void setPasswordcreation(Date passwordcreation) {
		this.passwordcreation = passwordcreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESETPASSTIME", nullable = false, length = 19)
	public Date getResetpasstime() {
		return this.resetpasstime;
	}

	public void setResetpasstime(Date resetpasstime) {
		this.resetpasstime = resetpasstime;
	}

	@Column(name = "PASSWORDINVALID")
	public Short getPasswordinvalid() {
		return this.passwordinvalid;
	}

	public void setPasswordinvalid(Short passwordinvalid) {
		this.passwordinvalid = passwordinvalid;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 256)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIELD4", nullable = false, length = 19)
	public Date getField4() {
		return this.field4;
	}

	public void setField4(Date field4) {
		this.field4 = field4;
	}

}
