package com.letbeclear.model;
// Generated Feb 5, 2018 1:20:43 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPost generated by hbm2java
 */
@Entity
@Table(name = "user_post", catalog = "letbeclear")
public class UserPost implements java.io.Serializable {

	private Integer postId;
	private Users users;
	private String imagePath;
	private String primaryImage;
	private int noOfImage;
	private String description;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private Date postTime;
	private String field1;
	private String field2;
	private String field3;
	private Integer field4;
	private Date field5;
	private String postLoc;
	private Set<PostLike> postLikes = new HashSet<PostLike>(0);
	private Set<PostComment> postComments = new HashSet<PostComment>(0);
	private Set<PostLike> postLikes_1 = new HashSet<PostLike>(0);

	public UserPost() {
	}

	public UserPost(Users users, int noOfImage, Date postTime, Date field5) {
		this.users = users;
		this.noOfImage = noOfImage;
		this.postTime = postTime;
		this.field5 = field5;
	}

	public UserPost(Users users, String imagePath, String primaryImage, int noOfImage, String description,
			BigDecimal latitude, BigDecimal longitude, Date postTime, String field1, String field2, String field3,
			Integer field4, Date field5, String postLoc, Set<PostLike> postLikes, Set<PostComment> postComments,
			Set<PostLike> postLikes_1) {
		this.users = users;
		this.imagePath = imagePath;
		this.primaryImage = primaryImage;
		this.noOfImage = noOfImage;
		this.description = description;
		this.latitude = latitude;
		this.longitude = longitude;
		this.postTime = postTime;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
		this.field5 = field5;
		this.postLoc = postLoc;
		this.postLikes = postLikes;
		this.postComments = postComments;
		this.postLikes_1 = postLikes_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "POST_ID", unique = true, nullable = false)
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "IMAGE_PATH", length = 512)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "PRIMARY_IMAGE", length = 512)
	public String getPrimaryImage() {
		return this.primaryImage;
	}

	public void setPrimaryImage(String primaryImage) {
		this.primaryImage = primaryImage;
	}

	@Column(name = "NO_OF_IMAGE", nullable = false)
	public int getNoOfImage() {
		return this.noOfImage;
	}

	public void setNoOfImage(int noOfImage) {
		this.noOfImage = noOfImage;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LATITUDE", precision = 10, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 11, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "POST_TIME", nullable = false, length = 19)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Column(name = "FIELD1", length = 256)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 256)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 512)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@Column(name = "FIELD4")
	public Integer getField4() {
		return this.field4;
	}

	public void setField4(Integer field4) {
		this.field4 = field4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIELD5", nullable = false, length = 19)
	public Date getField5() {
		return this.field5;
	}

	public void setField5(Date field5) {
		this.field5 = field5;
	}

	@Column(name = "POST_LOC", length = 512)
	public String getPostLoc() {
		return this.postLoc;
	}

	public void setPostLoc(String postLoc) {
		this.postLoc = postLoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPost")
	public Set<PostLike> getPostLikes() {
		return this.postLikes;
	}

	public void setPostLikes(Set<PostLike> postLikes) {
		this.postLikes = postLikes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPost")
	public Set<PostComment> getPostComments() {
		return this.postComments;
	}

	public void setPostComments(Set<PostComment> postComments) {
		this.postComments = postComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPost")
	public Set<PostLike> getPostLikes_1() {
		return this.postLikes_1;
	}

	public void setPostLikes_1(Set<PostLike> postLikes_1) {
		this.postLikes_1 = postLikes_1;
	}

}
